[package]
name = "equihash"
version = "0.1.0"
authors = ["Floyd Z <floyd.zweydinger@rub.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blake2b_simd = "0.5"
blake2s_simd = "0.5"
byteorder = "1"